version: "3.9"

services:
  node_process:
    build:
      context: ..
      dockerfile: ./deploy/docker/Dockerfile.node
    command: sleep 100000 # python3 main.py
    environment:
      DISPLAY: host.docker.internal:0
      OPEN3D_CPU_RENDERING: 1
      LIBGL_ALWAYS_INDIRECT: 1
    volumes:
      - ../Node:/Node
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/.Xauthority
