version: "3.9"

services:
  ros_node_new:
    stdin_open: true
    tty: true
    build:
      context: ..
      dockerfile: ./deploy/docker/Dockerfile.ros-node2
    # command: sleep 10000000
    environment:
      DISPLAY: :0 # host.docker.internal:0
      OPEN3D_CPU_RENDERING: 1
      LIBGL_ALWAYS_INDIRECT: 1
      ROS_DOMAIN_ID: 1
    volumes:
      - ../Node/ros:/Node
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority

volumes: 
  data: {}