version: "3.9"

services:
  ros_node:
    build:
      context: ..
      dockerfile: ./deploy/docker/Dockerfile.ros-node
    command: sleep 10000000 #ros2 launch webots_ros2_epuck robot_launch.py
    environment:
      DISPLAY: host.docker.internal:0
      OPEN3D_CPU_RENDERING: 1
      LIBGL_ALWAYS_INDIRECT: 1
      ROS_DOMAIN_ID: 1
    volumes:
      - ../Node/ros:/Node
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/.Xauthority


volumes: 
  data: {}